/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CalendarSingleListing {
    /** Date with format YYYY-MM-DD */
    date?: string;
    listingId?: string;
    /** Listing's currency value. */
    currency?: string;
    /** Price in the listing's currency. */
    price?: number;
    /** Flag which shows whether listing is set to base price. */
    isBasePrice?: boolean;
    /** Min nights value. */
    minNights?: number;
    /** Flag which shows whether listing is set to base min night. */
    isBaseMinNights?: boolean;
    /** Status value, enum: available, unavailable. */
    status?: string;
    /** Allotment value for parent listing. */
    allotment?: number;
    blocks?: Record<string, unknown>;
    blockRefs?: string[];
    reservationId?: string;
    reservation?: Record<string, unknown>;
    /** Closed To Arrival value */
    cta?: boolean;
    /** Closed To Departure value */
    ctd?: boolean;
}
