/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CalendarStatus = "available" | "unavailable";

export const CalendarStatus = {
    Available: "available",
    Unavailable: "unavailable",
} as const;
