/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class GuestyApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, GuestyApiTimeoutError.prototype);
    }
}
