/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { GuestyApi } from "@fern-api/guesty";
import * as core from "../../../../core";

export const CalendarStatus: core.serialization.Schema<serializers.CalendarStatus.Raw, GuestyApi.CalendarStatus> =
    core.serialization.enum_(["available", "unavailable"]);

export declare namespace CalendarStatus {
    type Raw = "available" | "unavailable";
}
