/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { GuestyApi } from "@fern-api/guesty";
import * as core from "../../../../core";

export const CalendarSingleListing: core.serialization.ObjectSchema<
    serializers.CalendarSingleListing.Raw,
    GuestyApi.CalendarSingleListing
> = core.serialization.object({
    date: core.serialization.string().optional(),
    listingId: core.serialization.string().optional(),
    currency: core.serialization.string().optional(),
    price: core.serialization.number().optional(),
    isBasePrice: core.serialization.boolean().optional(),
    minNights: core.serialization.number().optional(),
    isBaseMinNights: core.serialization.boolean().optional(),
    status: core.serialization.string().optional(),
    allotment: core.serialization.number().optional(),
    blocks: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    blockRefs: core.serialization.list(core.serialization.string()).optional(),
    reservationId: core.serialization.string().optional(),
    reservation: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    cta: core.serialization.boolean().optional(),
    ctd: core.serialization.boolean().optional(),
});

export declare namespace CalendarSingleListing {
    interface Raw {
        date?: string | null;
        listingId?: string | null;
        currency?: string | null;
        price?: number | null;
        isBasePrice?: boolean | null;
        minNights?: number | null;
        isBaseMinNights?: boolean | null;
        status?: string | null;
        allotment?: number | null;
        blocks?: Record<string, unknown> | null;
        blockRefs?: string[] | null;
        reservationId?: string | null;
        reservation?: Record<string, unknown> | null;
        cta?: boolean | null;
        ctd?: boolean | null;
    }
}
