/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CalendarSingleListingRequest {
    /**
     * First day to be returned (format: YYYY-MM-DD)
     */
    startDate: string;
    /**
     * Last day to be returned (format: YYYY-MM-DD)
     */
    endDate: string;
    /**
     * Return day objects including allotment
     */
    includeAllotment?: boolean;
}
