/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveMultipleCalendarsRequest {
    /**
     * Listing IDs (comma separated)
     */
    listingIds: string;
    /**
     * First day to be returned (format: YYYY-MM-DD)
     */
    startDate: string;
    /**
     * Last day to be returned (format: YYYY-MM-DD)
     */
    endDate: string;
}
