/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { GuestyApi } from "@fern-api/guesty";

export interface UpdateCalendarSingleListingRequest {
    startDate: string;
    endDate: string;
    status?: GuestyApi.CalendarStatus;
    price?: number;
    isBasePrice?: boolean;
    minNights?: number;
    isBaseMinNights?: boolean;
    note?: string;
    cta?: boolean;
    ctd?: boolean;
    useChildValues?: boolean;
}
