/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const GuestyApiEnvironment = {
    Production: "https://open-api.guesty.com/v1",
} as const;

export type GuestyApiEnvironment = typeof GuestyApiEnvironment.Production;
